baseURL = "https://masanam77.github.io/shiba.labo"
title = "Shiba.Labo"
theme = "ananke"
languageCode = "ja-jp"
summarylength = 100
publishDir              = "docs"
canonifyurls = true
draft = false

SEOTitle = "楽しみだね"

slogan = "ささやかに暮らす"

description = "artとか文学とか漫画とかそのあたり書きます"

SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
#enableRobotsTXT = true

[outputs]
    page = [ "HTML" , "AMP"  ]

[params.social]
  facebook      = "full profile url in facebook"
  #googleplus    = "full profile url in googleplus"
  email         = "shibamac@icloud.com"
  twitter       = "full profile url in twitter"

[params]
slogan = "ささやかに暮らす"
description = "artとか文学とか漫画とかそのあたり書きます"
#author = "shibawan"
#authorLink = ""
#bio = ["年とってから美術の勉強中"]
copyright = ["&copy; 2021 shiba","Nederburg Hugo Theme by [Appernetic]().","A port of Tracks by Compete Themes."]
#choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
#background_color_class = "bg-dark-blue { background-color: #00449E }"
background_color_class = "bg-blue"
#text = "washed-green { color: #E8FDF5 }"
#featured_image = "/images/gohugo-default-sample-hero-image.jpg"
#featured_image = "/images/gohugo-default-img1.jpg"

[permalinks]
    post = "/:section/:year/:month/:filename"

[menu]
[[menu.main]]
  name = "art"
  url1 = "contact/"
  weight = 1

[[menu.main]]
   name = "Life"
   url1 = "contact/post/"
   weight = 2

[[menu.main]]
     name = "about"
     url1 = "about/"
     weight = 3
[[menu.main]]
       name = "culture"
       url1 = "contact/"
       weight = 4

[[menu.main]]
       name = "book"
       url1 = "contact/"
       weight = 5

[taxsonomies]
category = "categories"
tag = "tags"
author = "authors"
