baseURL = "https://masanam77.github.io/ndttc.nt"
title = "高体連新潟地区卓球専門部"
theme = "ananke"
languageCode = "ja-jp"
summarylength = 100
publishDir = "docs"
canonifyurls = true
draft = false

SEOTitle = "正式なHPができるまでの臨時連絡板です。"

slogan = "期間限定版です"

description = "期間を限定して公開します。"

SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
#enableRobotsTXT = true
disqusShortname = "ndttc"

[outputs]
    page = [ "HTML" , "AMP"  ]

[params.social]
  #facebook      = "full profile url in facebook"
  #googleplus    = "full profile url in googleplus"
  email         = "shibamac@me.com"
  #twitter       = "full profile url in twitter"

[params]
slogan = "公開情報のみお知らせします。"
description = "期間限定版です。大会前などのみに公開します。"
author = "新潟地区地区代表"
#authorLink = ""
#bio = ["年とってから美術の勉強中"]
copyright = ["&copy; 2021 shiba","Nederburg Hugo Theme by [Appernetic]().","A port of Tracks by Compete Themes."]
#choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
#background_color_class = "bg-dark-blue { background-color: #00449E }"
background_color_class = "bg-blue"
#text = "washed-green { color: #E8FDF5 }"
#featured_image = "/images/gohugo-default-sample-hero-image.jpg"
#featured_image = "/images/gohugo-default-img1.jpg"
commentoEnable = true

[permalinks]
    post = "/:section/:year/:month/:filename"

[menu]

[[menu.main]]
  name = ""
  pre = "<i class='fa fa-heart'></i>"
  weight = 1
  identifier = ""
  url1 = ""

[taxsonomies]
category = "categories"
tag = "tags"
author = "authors"
